name: CI

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: SimpleAppCdCi
          dockerfile: SimpleAppCdCi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simpleappcdci:latest
  deploy:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/simpleappcdci:latest
            docker compose up